// <auto-generated />
using System;
using BlazorServerApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServerApp.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20230702185404_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorServerApp.Models.Car", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double?>("km")
                        .HasColumnType("float")
                        .HasColumnName("km");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int?>("year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("id")
                        .HasName("PK__Car__3213E83FCD6B2901");

                    b.ToTable("Car", (string)null);
                });

            modelBuilder.Entity("BlazorServerApp.Models.Contact", b =>
                {
                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("firstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("firstName");

                    b.Property<string>("lastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lastName");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("BlazorServerApp.Models.Revenue", b =>
                {
                    b.Property<double>("Year")
                        .HasColumnType("float")
                        .HasColumnName("year");

                    b.Property<double?>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("amount");

                    b.HasKey("Year")
                        .HasName("PK__Revenue__809A238AEB416AB5");

                    b.ToTable("Revenue", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
